import Foundation

/// The bundled emoji set ships names only, so common search words live here.
/// Keys are base emoji (variant forms inherit through their group).
enum EmojiKeywords {
    static let map: [String: String] = [
        "😀": "happy smile",
        "😃": "happy smile",
        "😄": "happy smile laugh",
        "😁": "happy smile grin",
        "😆": "laugh happy",
        "😅": "laugh sweat",
        "🤣": "laugh funny",
        "😂": "laugh cry funny",
        "🙂": "smile happy",
        "😊": "happy smile blush",
        "😍": "love heart",
        "🥰": "love heart",
        "😘": "love kiss",
        "😢": "sad cry",
        "😭": "cry sad",
        "😔": "sad",
        "😞": "sad",
        "😡": "angry mad",
        "🤔": "think",
        "😴": "sleep tired",
        "❤": "love heart",
        "🧡": "love heart",
        "💛": "love heart",
        "💚": "love heart",
        "💙": "love heart",
        "💜": "love heart",
        "🖤": "love heart",
        "💔": "heart sad broken",
        "🔥": "fire hot lit",
        "⭐": "star favorite",
        "🌟": "star sparkle",
        "✨": "star sparkle magic",
        "💼": "work job briefcase",
        "🏢": "work office building",
        "💰": "money cash finance",
        "💵": "money cash dollar",
        "💳": "money card payment",
        "🍕": "food pizza",
        "🍔": "food burger",
        "🍎": "food apple fruit",
        "🍜": "food noodles",
        "☕": "coffee drink food",
        "🐱": "cat pet animal",
        "🐈": "cat pet animal",
        "🐶": "dog pet animal",
        "🐕": "dog pet animal",
        "🚗": "car drive auto",
        "🚙": "car drive auto",
        "🏠": "home house",
        "🏡": "home house garden",
        "🎮": "game gaming play",
        "🕹": "game arcade play",
        "🎵": "music song audio",
        "🎶": "music song audio",
        "🎧": "music headphones audio",
        "📚": "book books read study",
        "📖": "book read",
        "💻": "code laptop computer work",
        "🖥": "code computer desktop",
        "👨‍💻": "code developer programmer work",
        "👩‍💻": "code developer programmer work",
        "🧑‍💻": "code developer programmer work",
        "⌨": "code keyboard type"
    ]
}
